name: Publish package to GitHub Packages

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Bump package version
        id: version
        run: |
          git config --global user.email "yury.lvn@mail.ru"
          git config --global user.name "pieceowater"
          npm version patch
          echo ::set-output name=version::$(npm --silent run version)

      - name: Authenticate with GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.NPM_TOKEN }}

      - name: Build and publish package
        run: |
          npm run build
          echo "//npm.pkg.github.com/:_authToken=${{secrets.NPM_TOKEN}}" >> .npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Update package.json and push changes
        uses: EndBug/version-check@v2
        with:
          tag: '${{ github.ref }}'
          push: true
          token: ${{ secrets.NPM_TOKEN }}
