name: Create Release

on:
  push:
    branches: [main]

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Increment version
        id: ver
        run: |
          npm version patch --no-git-tag-version
          version=$(node -p "require('./package.json').version")
          echo "v=$version" >> $GITHUB_OUTPUT

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}
        with: 
          tag_name: ${{ steps.ver.outputs.v }}
          release_name: Release v${{ steps.ver.outputs.v }}
          draft: false
          prerelease: false

      - name: Update package.json
        run: |
          version=${{ steps.ver.outputs.v }}
          sed -i "s/\"version\": \".*\"/\"version\": \"$version\"/" package.json
          sed -i "s/\"version\": \".*\"/\"version\": \"$version\"/" package-lock.json
          git config --global user.email "yury.lvn@mail.ru"
          git config --global user.name "pieceowater"
          git add package.json
          git commit -m "Increment version to $version" -m "[skip ci]"
          git push

