name: Create new release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Get latest tag
        run: git fetch --tags
      - name: Set release version
        id: version
        run: echo "::set-output name=version::$(npm version patch | cut -c 2-)"

      - name: Create release
        uses: actions/create-release@v1
        env:
          TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            Changes in this release:
            - Add new feature X
            - Fix bug Y
          draft: false
          prerelease: false
