name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Get latest tag
        run: git fetch --tags
        
      - name: Set release version
        id: version
        run: |
          git config --global user.email "yury.lvn@mail.ru" |
          git config --global user.name "pieceowater" |
          echo $(npm version patch) 

#           echo "{version}={$(npm version patch | cut -c 2-)}" >> $GITHUB_OUTPUT 
#       - name: Create release
#         uses: actions/create-release@v1
#         with:
#           tag_name: ${{ steps.version.outputs.version }}
#           release_name: v${{ steps.version.outputs.version }}
#           body: |
#             Changes in this release:
#             - Add new feature
#             - Fix bug
#           draft: false
#           prerelease: false
#         env:
#           GITHUB_TOKEN: ${{ secrets.NPM_TOKEN }}
#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
